package es.org.greendaoexample.data.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import es.org.greendaoexample.data.db.Cliente;
import es.org.greendaoexample.data.db.Viaje;

import es.org.greendaoexample.data.db.dao.ClienteDao;
import es.org.greendaoexample.data.db.dao.ViajeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clienteDaoConfig;
    private final DaoConfig viajeDaoConfig;

    private final ClienteDao clienteDao;
    private final ViajeDao viajeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        viajeDaoConfig = daoConfigMap.get(ViajeDao.class).clone();
        viajeDaoConfig.initIdentityScope(type);

        clienteDao = new ClienteDao(clienteDaoConfig, this);
        viajeDao = new ViajeDao(viajeDaoConfig, this);

        registerDao(Cliente.class, clienteDao);
        registerDao(Viaje.class, viajeDao);
    }
    
    public void clear() {
        clienteDaoConfig.getIdentityScope().clear();
        viajeDaoConfig.getIdentityScope().clear();
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public ViajeDao getViajeDao() {
        return viajeDao;
    }

}
