package es.org.greendaoexample.data.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import es.org.greendaoexample.data.db.Cliente;

import es.org.greendaoexample.data.db.Viaje;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIAJE".
*/
public class ViajeDao extends AbstractDao<Viaje, Long> {

    public static final String TABLENAME = "VIAJE";

    /**
     * Properties of entity Viaje.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cliente_id = new Property(1, Long.class, "cliente_id", false, "CLIENTE_ID");
        public final static Property Destino = new Property(2, String.class, "destino", false, "DESTINO");
        public final static Property Dias = new Property(3, Integer.class, "dias", false, "DIAS");
        public final static Property Fecha_reserva = new Property(4, java.util.Date.class, "fecha_reserva", false, "FECHA_RESERVA");
    };

    private DaoSession daoSession;

    private Query<Viaje> cliente_ViajeListQuery;

    public ViajeDao(DaoConfig config) {
        super(config);
    }
    
    public ViajeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIAJE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CLIENTE_ID\" INTEGER," + // 1: cliente_id
                "\"DESTINO\" TEXT," + // 2: destino
                "\"DIAS\" INTEGER," + // 3: dias
                "\"FECHA_RESERVA\" INTEGER);"); // 4: fecha_reserva
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_VIAJE_CLIENTE_ID ON VIAJE" +
                " (\"CLIENTE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIAJE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Viaje entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long cliente_id = entity.getCliente_id();
        if (cliente_id != null) {
            stmt.bindLong(2, cliente_id);
        }
 
        String destino = entity.getDestino();
        if (destino != null) {
            stmt.bindString(3, destino);
        }
 
        Integer dias = entity.getDias();
        if (dias != null) {
            stmt.bindLong(4, dias);
        }
 
        java.util.Date fecha_reserva = entity.getFecha_reserva();
        if (fecha_reserva != null) {
            stmt.bindLong(5, fecha_reserva.getTime());
        }
    }

    @Override
    protected void attachEntity(Viaje entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Viaje readEntity(Cursor cursor, int offset) {
        Viaje entity = new Viaje( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // cliente_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // destino
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // dias
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // fecha_reserva
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Viaje entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCliente_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDestino(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDias(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setFecha_reserva(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Viaje entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Viaje entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "viajeList" to-many relationship of Cliente. */
    public List<Viaje> _queryCliente_ViajeList(Long cliente_id) {
        synchronized (this) {
            if (cliente_ViajeListQuery == null) {
                QueryBuilder<Viaje> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Cliente_id.eq(null));
                cliente_ViajeListQuery = queryBuilder.build();
            }
        }
        Query<Viaje> query = cliente_ViajeListQuery.forCurrentThread();
        query.setParameter(0, cliente_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClienteDao().getAllColumns());
            builder.append(" FROM VIAJE T");
            builder.append(" LEFT JOIN CLIENTE T0 ON T.\"CLIENTE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Viaje loadCurrentDeep(Cursor cursor, boolean lock) {
        Viaje entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Cliente cliente = loadCurrentOther(daoSession.getClienteDao(), cursor, offset);
        entity.setCliente(cliente);

        return entity;    
    }

    public Viaje loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Viaje> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Viaje> list = new ArrayList<Viaje>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Viaje> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Viaje> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
